name: chinese_master
description: "An offline-first HSK Chinese learning app."
publish_to: 'none'

version: 1.0.1+6

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  flutter_keyboard_visibility: ^6.0.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  http: ^1.2.2
  audioplayers: ^6.7.1
  speech_to_text: ^7.4.0
  permission_handler: ^11.3.1
  path_drawing: ^1.0.1
  change_app_package_name: ^1.5.0
  image_picker: ^1.1.2
  flutter_tts: ^4.1.0
  in_app_purchase: ^3.3.0
  loader_overlay: ^5.0.0
  flutter_screenutil: ^5.9.3
  cherry_toast: ^1.13.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.3
  flutter_lints: ^5.0.0
  sqlite3: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/database/chinese_v2_sheet1_only.db
    - assets/logo/logo.png

  fonts:
    - family: PinyinFont
      fonts:
        - asset: assets/fonts/Pinyinfont_V2.ttf
    - family: FZKaiTiPinyin
      fonts:
        - asset: assets/fonts/fz_kaiti_pinyin_01.ttf
    - family: FZKaiTiPinyin_1
      fonts:
        - asset: assets/fonts/fz_kaiti_pinyin_01_1.ttf
    - family: PinyinOk
      fonts:
        - asset: assets/fonts/Pinyinok.ttf

icons_launcher:
  image_path: "assets/logo/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
