#storePassword=123456
#keyPassword=123456
#keyAlias=chinesetypingpractice
#storeFile=chinesetypingpractice-release.jks
storePassword=123456
keyPassword=123456
keyAlias=flashlearn
storeFile=upload-keystore.jks
